name: app_movie_challenge
description: "An app that displays the list of nominees and winners in the Worst Picture category of the Golden Raspberry Awards."
publish_to: 'none'

version: 0.0.1
 
environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.21.0 <3.23.0"

dependencies:
  flutter:
    sdk: flutter

  #
  # For UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  timeago: ^3.6.1
  flutter_keyboard_visibility: ^6.0.0

  #
  # For navigation.
  go_router: ^14.2.1
  
  #
  # For Entity and Serialization.
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #
  # For State Management.
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  
  
  # For dependency injection.
  get_it: ^7.7.0
  injectable: ^2.4.1

  # For storage.
  flutter_secure_storage: ^9.0.0

  # For network.
  dio: ^5.4.3+1

  #
  # For permisstions device.
  permission_handler: ^11.3.1
  app_tracking_transparency: ^2.0.4
  
  #
  # For device access.
  package_info_plus: ^8.0.0

  #
  # For localization.
  intl: ">=0.18.0 <0.20.0"

  #
  # For logs.
  logger: ^2.2.0
 

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #
  # For localization.
  intl_utils: ^2.8.7

  #
  # For dependency injection.
  injectable_generator: ^2.6.1

  #
  # For code generation.
  build_runner: ^2.4.9

  #
  # For entities and serialization.
  json_serializable: ^6.7.1
  freezed: ^2.5.2

  #
  # For tests.
  faker: ^2.1.0
  mocktail: ^1.0.3
  http_mock_adapter: ^0.6.1

  #
  # For quality code.
  flutter_lints: ^3.0.0
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/brand/logo.png

flutter_intl:
  enabled: true 
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
